{{- if .Values.database.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
    name: domino-database-migrations-job
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 10
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: OnFailure
      containers:
      - name: database-migrations
        image: {{ .Values.rest.image }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: ["run_migrations.sh"]   # will sleep for 20 seconds, run migrations and create first user
        env:
          - name: DOMINO_DB_HOST
            value: {{ .Release.Name }}-postgres-service
          - name: DOMINO_DB_NAME
            value: {{ .Values.database.name }}
          - name: DOMINO_DB_USER
            value: {{ .Values.database.user }}
          - name: DOMINO_DB_PASSWORD
            value: {{ .Values.database.password }}
          - name: DOMINO_DB_PORT
            value: "5432"
{{- end }}