apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  restartPolicy: Never

  volumes:
    - name: shared-storage
      emptyDir: {}

  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: shared-storage
          mountPath: /shared_storage
          mountPropagation: HostToContainer
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"

    - name: sidecar-container
      image: ghcr.io/tauffer-consulting/domino-shared-storage-sidecar:latest
      securityContext:
        privileged: true
      # command: ["sh", "-c", "sleep 1h"]
      command: ["/bin/bash"]
      args:
        [
          "-c",
          "python mount_sources.py && ./sidecar_lifecycle.sh && python unmount_sources.py",
        ]
      # Neat idea from here: https://karlstoney.com/2017/03/01/fuse-mount-in-kubernetes/
      # lifecycle:
      #     postStart:
      #       exec:
      #         command: ["gcsfuse", "-o", "nonempty", "your-bucket-name", "/etc/letsencrypt"]
      #     preStop:
      #       exec:
      #         command: ["fusermount", "-u", "/etc/letsencrypt"]
      env:
        - name: SHARED_STORAGE_SOURCE_NAME
          value: ""
        - name: AWS_ACCESS_KEY_ID
          value: ""
        - name: AWS_SECRET_ACCESS_KEY
          value: ""
        - name: AWS_REGION_NAME
          value: ""
        - name: AWS_S3_BUCKET_NAME
          value: ""
        - name: REMOTE_BASE_FOLDER_PATH
          value: ""
      volumeMounts:
        - name: shared-storage
          mountPath: /shared_storage
          mountPropagation: Bidirectional
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
