apiVersion: v2
name: domino
description: A Helm chart for Domino
type: application
version: 0.1.11
appVersion: 0.1.11
home: https://github.com/Tauffer-Consulting/domino
sources:
  - https://github.com/Tauffer-Consulting/domino
