{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - name: {{ .Release.Name }}-frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          {{- if .Values.frontend.entrypointCommand }}
          command:
            {{ toYaml .Values.frontend.entrypointCommand | indent 12 }}
          args:
            ["-c","pnpm start"]
          {{- end }}
          env:
            - name: DOMINO_DEPLOY_MODE
              value: {{ .Values.frontend.deployMode }}
            - name: API_URL
              value: {{ .Values.frontend.apiUrl }}

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-service
spec:
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
  - port: 80
{{- end}}