apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  github_access_token_pieces: {{ .Values.github_access_token_pieces | b64enc }}
  github_access_token_workflows: {{ .Values.github_access_token_workflows | b64enc }}