name: Build and publish Domino Airflow development images

on:
  push:
    branches:
      - dev
    paths:
      - src/domino/**
      - Dockerfile-airflow-domino.dev
      - Dockerfile-domino-piece.gpu-dev
      - Dockerfile-domino-piece.dev

jobs:
  domino-airflow-base:
    name: Domino Airflow Base Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Domino Airflow Base image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/tauffer-consulting/domino-airflow-base:latest-dev
          context: .
          file: Dockerfile-airflow-domino.dev

  domino-base-piece:
    name: Domino Base Piece Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Domino Base Piece Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/tauffer-consulting/domino-base-piece:latest-dev
          context: .
          file: Dockerfile-domino-piece.dev

  domino-base-piece-gpu:
    name: Domino Base Piece GPU Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Domino Base Piece Image with GPU support
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/tauffer-consulting/domino-base-piece:gpu-dev
          context: .
          file: Dockerfile-domino-piece.gpu-dev

  domino-storage-sidecar:
    name: Domino Storage Sidecar Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Domino Storage Sidecar image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/tauffer-consulting/domino-shared-storage-sidecar:latest-dev
          context: src/domino/custom_operators/sidecar
          file: src/domino/custom_operators/sidecar/Dockerfile
