name: Build and publish Domino Airflow production images

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile-airflow-domino.prod
      - Dockerfile-domino-piece.gpu-prod
      - Dockerfile-domino-piece.prod
  workflow_run:
    workflows: ["Build and publish domino-py package"]
    branches: [main]
    types:
      - completed
    paths:
      - src/domino/**

jobs:
  domino-airflow-base:
    name: Domino Airflow Base Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Domino Airflow Base image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/tauffer-consulting/domino-airflow-base:latest
          context: .
          file: Dockerfile-airflow-domino.prod

  domino-base-piece:
    name: Domino Base Piece Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Domino Base Piece Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/tauffer-consulting/domino-base-piece:latest
          context: .
          file: Dockerfile-domino-piece.prod

  domino-base-piece-gpu:
    name: Domino Base Piece GPU Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Domino Base Piece Image with GPU support
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/tauffer-consulting/domino-base-piece:gpu
          context: .
          file: Dockerfile-domino-piece.gpu-prod

  domino-storage-sidecar:
    name: Domino Storage Sidecar Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Domino Storage Sidecar image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/tauffer-consulting/domino-shared-storage-sidecar:latest
          context: src/domino/custom_operators/sidecar
          file: src/domino/custom_operators/sidecar/Dockerfile

